import type { Metadata } from "next";
import "./globals.css";
import CustomLayout from "./CustomLayout";
import { AppProdiver } from "@/contexts";

export const metadata: Metadata = {
  title: "딸기 마켓",
  description: "Generated by KS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProdiver>
          <CustomLayout>{children}</CustomLayout>
        </AppProdiver>
      </body>
    </html>
  );
}
